version: v1.0
name: Deploy new image and restart
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      secrets:
        - name: remote-deploy-details
      jobs:
        - name: Pull image & restart bot
          commands:
            - chmod 400 /home/semaphore/.ssh/id_rsa
            - ssh-keyscan -p ${SSH_PORT} -H ${SSH_HOST} >> /home/semaphore/.ssh/known_hosts
            - ssh ${SSH_USER}@${SSH_HOST} -p ${SSH_PORT} "cd /opt/melijn-monitorinflux; sudo ./replaceImgPullAndRestart.sh melijn-monitorinflux-${SEMAPHORE_GIT_SHA}"